services:
  - type: web
    name: eventmanagementsystem
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn evmproject.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"